### ISSUE TITLE
Here, have a cpanfile

### ISSUE THREAD

**Issue by davehodg** [haukex/webperl#6]
Here, have a cpanfile:

requires 'Archive::Tar';
requires 'Archive::Zip';
requires 'Carp';
requires 'Cpanel::JSON::XS';
requires 'ExtUtils::MakeMaker';
requires 'File::Copy::Recursive';
requires 'File::Replace';
requires 'File::Temp';
requires 'FindBin';
requires 'Getopt::Long';
requires 'HTTP::Tiny';
requires 'Hash::Util';
requires 'IO::Socket::SSL';
requires 'IPC::Run3::Shell';
requires 'Net::SSLeay';
requires 'Path::Class';
requires 'Pod::Strip';
requires 'URI';
requires 'Time::HiRes';
requires 'Graph';
requires 'Memoize';
requires 'Memoize::Storable';
requires 'Devel::GlobalDestruction';
requires 'MetaCPAN::Client';
requires 'Module::CoreList';
requires 'IO::Select';
requires 'Socket';
requires 'Term::ANSIColor';
requires 'Module::Load::Conditional';
requires 'Plack';
requires 'Plack::App::Directory';
requires 'Plack::Builder';
requires 'Plack::MIME';
requires 'IPC::Open2';

For some odd reason I couldn't get github to play with me.:

```

> git push --set-upstream origin cpanfile
> ERROR: Permission to haukex/webperl.git denied to davehodg.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 

```

**Comment by haukex** [comment]
I was considering a `cpanfile`, thanks for getting it started!

As for the git issue, it sounds like you've checked out the original source, instead of your own fork - if you fork the repo, you can clone that or add it as a remote to your existing local working copy, start a new branch, commit your changes there, and then push to your fork. See e.g. <https://help.github.com/articles/working-with-forks/> and <https://help.github.com/articles/creating-a-pull-request-from-a-fork/>.

**Comment by davehodg** [comment]
That's not the way I usually work with GitHub. I usually do:

Clone master
Create a branch
Make changes
Commit/push the branch
Generate pull request.

**Comment by davehodg** [comment]
I've never done a fork on github before cloning/pulling. Oh, well.
